--!strict
-- GENERATED by tools/blender/build_cat.py — do not edit by hand.
-- Each mesh piece: the rig part it welds to, its centre in that part's
-- space, its size (studs) and whether it carries baked textures. The
-- meshes live in ReplicatedStorage.CatMeshes (imported from
-- assets/CatMeshes.glb).

return {
	{ Name = "HeadFur", Anchor = "Head", Center = Vector3.new(-0.0000, 0.0584, 0.0000), Size = Vector3.new(2.1551, 1.7540, 1.7559), Textured = true },
	{ Name = "Ears", Anchor = "Head", Center = Vector3.new(-0.0000, 0.7710, 0.0906), Size = Vector3.new(1.8000, 1.0168, 0.4102), Textured = true },
	{ Name = "InnerEar", Anchor = "Head", Center = Vector3.new(-0.0006, 0.8360, 0.0009), Size = Vector3.new(1.6138, 0.4303, 0.0637), Textured = false },
	{ Name = "EarTufts", Anchor = "Head", Center = Vector3.new(-0.0011, 0.7879, 0.0435), Size = Vector3.new(1.5286, 0.1979, 0.0797), Textured = false },
	{ Name = "EyeWhite", Anchor = "Head", Center = Vector3.new(0.0002, -0.0877, -0.7668), Size = Vector3.new(1.3694, 0.5275, 0.2070), Textured = false },
	{ Name = "Iris", Anchor = "Head", Center = Vector3.new(0.0000, -0.0883, -0.7796), Size = Vector3.new(1.3417, 0.4812, 0.1851), Textured = false },
	{ Name = "IrisGlow", Anchor = "Head", Center = Vector3.new(-0.0006, -0.2365, -0.7590), Size = Vector3.new(1.2642, 0.1838, 0.1543), Textured = false },
	{ Name = "Pupil", Anchor = "Head", Center = Vector3.new(-0.0002, -0.0767, -0.7998), Size = Vector3.new(1.2903, 0.4140, 0.1548), Textured = false },
	{ Name = "Shine", Anchor = "Head", Center = Vector3.new(0.0139, -0.0783, -0.7994), Size = Vector3.new(1.2558, 0.3934, 0.1746), Textured = false },
	{ Name = "Brows", Anchor = "Head", Center = Vector3.new(0.0001, 0.2920, -0.7596), Size = Vector3.new(1.0686, 0.0583, 0.1039), Textured = false },
	{ Name = "Nose", Anchor = "Head", Center = Vector3.new(-0.0019, -0.2542, -0.8207), Size = Vector3.new(0.0774, 0.0671, 0.0506), Textured = false },
	{ Name = "Mouth", Anchor = "Head", Center = Vector3.new(-0.0001, -0.3828, -0.7793), Size = Vector3.new(0.2152, 0.0591, 0.0410), Textured = false },
	{ Name = "Body", Anchor = "Root", Center = Vector3.new(-0.0000, -0.1501, -0.0000), Size = Vector3.new(1.3184, 1.1593, 1.0388), Textured = true },
	{ Name = "Shirt", Anchor = "Root", Center = Vector3.new(0.0012, -0.1292, -0.0111), Size = Vector3.new(1.2364, 1.1183, 0.9790), Textured = true },
	{ Name = "Jacket", Anchor = "Root", Center = Vector3.new(-0.0030, -0.0361, 0.0329), Size = Vector3.new(1.5769, 1.2902, 1.2728), Textured = true },
	{ Name = "Drawstrings", Anchor = "Root", Center = Vector3.new(0.0003, -0.0072, -0.5363), Size = Vector3.new(0.3356, 0.7317, 0.1490), Textured = true },
	{ Name = "DogTag", Anchor = "Root", Center = Vector3.new(-0.0212, 0.1331, -0.4246), Size = Vector3.new(0.2669, 0.4107, 0.2563), Textured = false },
	{ Name = "Pocket", Anchor = "Root", Center = Vector3.new(-0.4561, -0.4173, -0.5233), Size = Vector3.new(0.2990, 0.3017, 0.2017), Textured = true },
	{ Name = "Strap", Anchor = "Root", Center = Vector3.new(-0.0117, -0.0708, -0.0000), Size = Vector3.new(1.0428, 0.8605, 1.3143), Textured = true },
	{ Name = "Bag", Anchor = "Root", Center = Vector3.new(0.5670, -0.5901, -0.3732), Size = Vector3.new(0.4025, 0.3395, 0.3198), Textured = true },
	{ Name = "Hips", Anchor = "Root", Center = Vector3.new(-0.0000, -0.7400, 0.0200), Size = Vector3.new(1.1198, 0.3999, 0.8800), Textured = true },
	{ Name = "Sleeve", Anchor = "Arm", Center = Vector3.new(0.0007, 0.0591, -0.0015), Size = Vector3.new(0.4603, 0.6028, 0.4602), Textured = true },
	{ Name = "HoodieSleeve", Anchor = "Arm", Center = Vector3.new(0.0007, 0.0591, -0.0015), Size = Vector3.new(0.4603, 0.6028, 0.4602), Textured = true },
	{ Name = "Cuff", Anchor = "Arm", Center = Vector3.new(-0.0000, -0.2404, -0.0000), Size = Vector3.new(0.4939, 0.1193, 0.4939), Textured = true },
	{ Name = "Hand", Anchor = "Arm", Center = Vector3.new(-0.0000, -0.4397, -0.0199), Size = Vector3.new(0.3972, 0.3781, 0.3974), Textured = true },
	{ Name = "Leg", Anchor = "Leg", Center = Vector3.new(0.0001, -0.0749, -0.0990), Size = Vector3.new(0.5965, 0.7093, 0.7573), Textured = true },
	{ Name = "ShortsLeg", Anchor = "Leg", Center = Vector3.new(0.0021, 0.1185, -0.0003), Size = Vector3.new(0.7742, 0.3720, 0.7719), Textured = true },
	{ Name = "Tail", Anchor = "Tail", Center = Vector3.new(0.4353, -0.3103, -0.0306), Size = Vector3.new(1.0975, 0.9026, 0.8010), Textured = true },
}
