--!strict
-- GENERATED by tools/blender/build_cat.py — do not edit by hand.
-- Each mesh piece: the rig part it welds to, its centre in that part's
-- space and its size (Roblox studs). The meshes themselves live in
-- ReplicatedStorage.CatMeshes (imported from assets/CatMeshes.fbx).

return {
	{ Name = "HeadFur", Anchor = "Head", Center = Vector3.new(-0.0005, 0.2849, 0.0000), Size = Vector3.new(2.6349, 2.4480, 1.9974) },
	{ Name = "InnerEar", Anchor = "Head", Center = Vector3.new(-0.0021, 0.9495, -0.0886), Size = Vector3.new(1.9242, 0.5318, 0.1955) },
	{ Name = "EyeWhite", Anchor = "Head", Center = Vector3.new(0.0000, -0.0571, -0.8892), Size = Vector3.new(1.4938, 0.5677, 0.2028) },
	{ Name = "Iris", Anchor = "Head", Center = Vector3.new(-0.0006, -0.0566, -0.9000), Size = Vector3.new(1.4558, 0.5212, 0.1821) },
	{ Name = "IrisGlow", Anchor = "Head", Center = Vector3.new(-0.0000, -0.2053, -0.8891), Size = Vector3.new(1.3740, 0.2092, 0.1560) },
	{ Name = "Pupil", Anchor = "Head", Center = Vector3.new(-0.0004, -0.0318, -0.9245), Size = Vector3.new(1.3469, 0.3820, 0.1331) },
	{ Name = "Shine", Anchor = "Head", Center = Vector3.new(0.0160, -0.0437, -0.9251), Size = Vector3.new(1.3482, 0.3986, 0.1566) },
	{ Name = "Brows", Anchor = "Head", Center = Vector3.new(0.0002, 0.3437, -0.8592), Size = Vector3.new(1.1896, 0.0644, 0.1146) },
	{ Name = "ForeheadMark", Anchor = "Head", Center = Vector3.new(-0.0011, 0.6424, -0.7551), Size = Vector3.new(0.1801, 0.1480, 0.1334) },
	{ Name = "Nose", Anchor = "Head", Center = Vector3.new(-0.0019, -0.2713, -0.9403), Size = Vector3.new(0.0887, 0.0712, 0.0531) },
	{ Name = "Mouth", Anchor = "Head", Center = Vector3.new(-0.0000, -0.3932, -0.9105), Size = Vector3.new(0.2038, 0.0534, 0.0427) },
	{ Name = "Blush", Anchor = "Head", Center = Vector3.new(-0.0003, -0.2934, -0.7040), Size = Vector3.new(1.8518, 0.1651, 0.1725) },
	{ Name = "Body", Anchor = "Root", Center = Vector3.new(-0.0000, -0.2000, 0.0000), Size = Vector3.new(1.2979, 1.0000, 0.9997) },
	{ Name = "Shirt", Anchor = "Root", Center = Vector3.new(-0.0000, -0.1947, -0.0100), Size = Vector3.new(1.1961, 0.9495, 0.9395) },
	{ Name = "Jacket", Anchor = "Root", Center = Vector3.new(0.0000, -0.1001, 0.0404), Size = Vector3.new(1.4388, 1.3590, 1.2377) },
	{ Name = "Drawstrings", Anchor = "Root", Center = Vector3.new(0.0001, -0.0406, -0.4225), Size = Vector3.new(0.4683, 0.4397, 0.2003) },
	{ Name = "DogTag", Anchor = "Root", Center = Vector3.new(0.0003, 0.0377, -0.4205), Size = Vector3.new(0.2751, 0.3616, 0.2036) },
	{ Name = "Pocket", Anchor = "Root", Center = Vector3.new(-0.4506, -0.4486, -0.4043), Size = Vector3.new(0.3046, 0.2386, 0.2687) },
	{ Name = "Bag", Anchor = "Root", Center = Vector3.new(0.1260, -0.2397, 0.0217), Size = Vector3.new(1.4181, 1.0207, 1.3105) },
	{ Name = "Hips", Anchor = "Root", Center = Vector3.new(-0.0000, -0.6600, 0.0200), Size = Vector3.new(1.0399, 0.4000, 0.8398) },
	{ Name = "Sleeve", Anchor = "Arm", Center = Vector3.new(0.0002, 0.0401, -0.0001), Size = Vector3.new(0.4765, 0.7179, 0.4769) },
	{ Name = "Cuff", Anchor = "Arm", Center = Vector3.new(0.0000, -0.2600, 0.0001), Size = Vector3.new(0.4643, 0.1398, 0.4637) },
	{ Name = "Hand", Anchor = "Arm", Center = Vector3.new(-0.0000, -0.4397, -0.0199), Size = Vector3.new(0.3972, 0.3781, 0.3974) },
	{ Name = "Leg", Anchor = "Leg", Center = Vector3.new(0.0001, -0.0749, -0.0990), Size = Vector3.new(0.5965, 0.7093, 0.7573) },
	{ Name = "ShortsLeg", Anchor = "Leg", Center = Vector3.new(0.0000, 0.1001, 0.0000), Size = Vector3.new(0.6579, 0.4395, 0.6579) },
	{ Name = "Tail", Anchor = "Tail", Center = Vector3.new(0.4171, -0.3021, -0.0486), Size = Vector3.new(1.0673, 0.8905, 0.7627) },
}
