--!strict
-- GENERATED by tools/blender/build_cat.py — do not edit by hand.
-- Each mesh piece: the rig part it welds to, its centre in that part's
-- space, its size (studs) and whether it carries baked textures. The
-- meshes live in ReplicatedStorage.CatMeshes (imported from
-- assets/CatMeshes.glb).

return {
	{ Name = "HeadFur", Anchor = "Head", Center = Vector3.new(-0.0002, 0.0582, -0.0000), Size = Vector3.new(2.4486, 1.7545, 1.7566), Textured = true },
	{ Name = "Ears", Anchor = "Head", Center = Vector3.new(-0.0000, 0.8288, 0.0907), Size = Vector3.new(1.9617, 1.1811, 0.4629), Textured = true },
	{ Name = "InnerEar", Anchor = "Head", Center = Vector3.new(-0.0001, 0.9086, 0.0018), Size = Vector3.new(1.7534, 0.4878, 0.0623), Textured = false },
	{ Name = "EarTufts", Anchor = "Head", Center = Vector3.new(0.0001, 0.8460, 0.0198), Size = Vector3.new(1.8221, 0.3136, 0.1453), Textured = false },
	{ Name = "EyeWhite", Anchor = "Head", Center = Vector3.new(-0.0001, -0.0969, -0.7579), Size = Vector3.new(1.3951, 0.5398, 0.2216), Textured = false },
	{ Name = "Iris", Anchor = "Head", Center = Vector3.new(0.0002, -0.0978, -0.7696), Size = Vector3.new(1.3624, 0.4874, 0.2022), Textured = false },
	{ Name = "IrisGlow", Anchor = "Head", Center = Vector3.new(0.0016, -0.2459, -0.7523), Size = Vector3.new(1.3116, 0.1934, 0.1589), Textured = false },
	{ Name = "Pupil", Anchor = "Head", Center = Vector3.new(-0.0007, -0.0877, -0.7937), Size = Vector3.new(1.3154, 0.4224, 0.1635), Textured = false },
	{ Name = "Shine", Anchor = "Head", Center = Vector3.new(0.0149, -0.0885, -0.7930), Size = Vector3.new(1.2789, 0.3962, 0.1831), Textured = false },
	{ Name = "Brows", Anchor = "Head", Center = Vector3.new(0.0001, 0.2923, -0.7597), Size = Vector3.new(1.0686, 0.0580, 0.1041), Textured = false },
	{ Name = "Nose", Anchor = "Head", Center = Vector3.new(-0.0020, -0.2542, -0.8207), Size = Vector3.new(0.0774, 0.0671, 0.0506), Textured = false },
	{ Name = "Mouth", Anchor = "Head", Center = Vector3.new(-0.0000, -0.3928, -0.7733), Size = Vector3.new(0.2155, 0.0591, 0.0417), Textured = false },
	{ Name = "Body", Anchor = "Root", Center = Vector3.new(-0.0000, -0.1501, -0.0000), Size = Vector3.new(1.3184, 1.1593, 1.0388), Textured = false },
	{ Name = "Shirt", Anchor = "Root", Center = Vector3.new(-0.0000, -0.1500, -0.0101), Size = Vector3.new(1.2162, 1.0777, 0.9583), Textured = true },
	{ Name = "Jacket", Anchor = "Root", Center = Vector3.new(-0.0000, -0.0400, 0.0612), Size = Vector3.new(1.4790, 1.5193, 1.3151), Textured = true },
	{ Name = "Drawstrings", Anchor = "Root", Center = Vector3.new(0.0001, -0.0027, -0.4324), Size = Vector3.new(0.3098, 0.6347, 0.2178), Textured = false },
	{ Name = "DogTag", Anchor = "Root", Center = Vector3.new(-0.0001, 0.1307, -0.4182), Size = Vector3.new(0.2920, 0.4156, 0.2472), Textured = false },
	{ Name = "Pocket", Anchor = "Root", Center = Vector3.new(-0.4706, -0.4284, -0.4115), Size = Vector3.new(0.3035, 0.2396, 0.2663), Textured = false },
	{ Name = "Bag", Anchor = "Root", Center = Vector3.new(0.1251, -0.1794, 0.0186), Size = Vector3.new(1.4598, 1.1012, 1.3745), Textured = false },
	{ Name = "Hips", Anchor = "Root", Center = Vector3.new(-0.0000, -0.7200, 0.0200), Size = Vector3.new(1.0399, 0.4000, 0.8399), Textured = false },
	{ Name = "Sleeve", Anchor = "Arm", Center = Vector3.new(0.0002, 0.0401, -0.0001), Size = Vector3.new(0.4765, 0.7179, 0.4769), Textured = false },
	{ Name = "HoodieSleeve", Anchor = "Arm", Center = Vector3.new(0.0002, 0.0401, -0.0001), Size = Vector3.new(0.4765, 0.7179, 0.4769), Textured = true },
	{ Name = "Cuff", Anchor = "Arm", Center = Vector3.new(0.0000, -0.2600, 0.0001), Size = Vector3.new(0.4643, 0.1398, 0.4637), Textured = false },
	{ Name = "Hand", Anchor = "Arm", Center = Vector3.new(-0.0000, -0.4398, -0.0200), Size = Vector3.new(0.3972, 0.3781, 0.3974), Textured = true },
	{ Name = "Leg", Anchor = "Leg", Center = Vector3.new(0.0001, -0.0749, -0.0990), Size = Vector3.new(0.5965, 0.7093, 0.7573), Textured = true },
	{ Name = "ShortsLeg", Anchor = "Leg", Center = Vector3.new(0.0000, 0.1001, 0.0000), Size = Vector3.new(0.6579, 0.4395, 0.6579), Textured = false },
	{ Name = "Tail", Anchor = "Tail", Center = Vector3.new(0.5611, -0.3128, -0.0735), Size = Vector3.new(1.3476, 0.9410, 0.9043), Textured = true },
}
